title: 小刀子飞飞的博客
excerpt_separator: <!--more-->
remote_theme: chesterhow/tale

permalink: /:year-:month-:day/:title
paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
        layout: "post"
